# Generated by Django 2.2.24 on 2021-11-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20211120_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasanger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=64)),
                ('Last_Name', models.CharField(max_length=64)),
                ('flight', models.ManyToManyField(blank=True, related_name='Passanger', to='flight.Flight')),
            ],
        ),
    ]
