# Generated by Django 2.2.24 on 2021-11-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_auto_20211126_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='Fruits',
            new_name='Fruit',
        ),
        migrations.AlterField(
            model_name='add',
            name='fruits',
            field=models.ManyToManyField(blank=True, related_name='addfruits', to='Market.Fruits'),
        ),
    ]
