# Generated by Django 2.2.24 on 2021-11-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_auto_20211126_0901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add',
        ),
    ]
